name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' # You can specify another version like 8 or 11

    # Step 3: Compile the Java program
    - name: Compile Java program
      run: javac helloworld.java

    # Step 4: Run the Java program
    - name: Run Java program
      run: java helloworld
